### ISSUE TITLE
README Link to sil.org is broken

### ISSUE THREAD

**Issue by RedactedCode** [dereckson/extract-proper-nouns#3]
Link to sil.org is broken - returns a 404.
A quick look over the sil.org site doesn't reveal any english wordlists

**Comment by dereckson** [comment]
When you encounter a broken link, you can try on Internet Archive (archive.org) to see if you can get a replacement.

That gives:
http://web.archive.org/web/20141122213941/http://www-01.sil.org/linguistics/wordlists/english/

Google seems to currently index http://www-01.sil.org/linguistics/etext.html but it's also a 404 in their current CDN.
